@startuml

skinparam packageStyle frame
package "Use case: Manage own artists"  {
    left to right direction

    :Artist Manager: as AM

    rectangle "Music Streaming App" {
        usecase "Add artist" as UC1
        usecase "Manage own artist's song" as UC2
        usecase "Manage own artist's album" as UC3
        usecase "Update own artist" as UC4
        usecase "Delete own artist" as UC5
    }

    AM --> UC1
    AM --> UC2
    AM --> UC3
    AM --> UC4
    AM --> UC5
}

@enduml